builds:
  - main: ./cmd/momo
    ldflags:
      - -s -w -X github.com/frantjc/momo.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.Dockerfile
    image_templates:
      - ghcr.io/frantjc/momo:{{ .RawVersion }}
      - ghcr.io/frantjc/momo:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/momo:{{ .Major }}
      - ghcr.io/frantjc/momo:latest
