version: 2
builds:
  - main: ./cmd/appa
    id: appa
    binary: appa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/kubectl-upload_app
    id: kubectl-upload_app
    binary: kubectl-upload_app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/momo
    id: momo
    binary: momo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.Dockerfile
    image_templates:
      - ghcr.io/frantjc/momo:{{ .RawVersion }}
      - ghcr.io/frantjc/momo:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/momo:{{ .Major }}
      - ghcr.io/frantjc/momo:latest
    extra_files:
      - app/
      - public/
      - package.json
      - postcss.config.js
      - server.js
      - tsconfig.json
      - vite.config.ts
      - yarn.lock
