services:
  momo-ctrl:
    build: .
    command:
      - -VV
      - ctrl
    volumes:
      - ${KUBECONFIG:-~/.kube/config}:/root/.kube/config
    depends_on:
      - minio
  momo-srv:
    build: .
    command:
      - -VV
      - --path=/api/v1
      - srv
      - node
      - /app/server.js
    volumes:
      - ${KUBECONFIG:-~/.kube/config}:/root/.kube/config
    ports:
      - 8080:8080
    depends_on:
      - minio
  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -c
      - |
        mkdir -p /data/default
        minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: momominio
      MINIO_ROOT_PASSWORD: momominio
