version: "3.4"

services:
  momo:
    image: ghcr.io/frantjc/momo
    build: .
    ports:
      - 8080:8080
    command:
      - -VV
      - --db=postgres://postgres:postgres@postgres?sslmode=disable
      - --blob=file:///var/lib/momo
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
