---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - momo.frantj.cc
  resources:
  - apks
  - buckets
  - ipas
  - mobileapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - momo.frantj.cc
  resources:
  - apks/finalizers
  - buckets/finalizers
  - ipas/finalizers
  - mobileapps/finalizers
  verbs:
  - update
- apiGroups:
  - momo.frantj.cc
  resources:
  - apks/status
  - buckets/status
  - ipas/status
  - mobileapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
