name: CI
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/frantjc/momo:${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/frantjc/momo:${{ github.sha }}
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: |
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      momo:
        image: ghcr.io/frantjc/momo:${{ github.sha }}
        ports:
          - 8080:8080
        env:
          MOMO_DB_URL: postgres://postgres:postgres@postgres?sslmode=disable
          MOMO_VERBOSE: "1"
        options: |
          --health-cmd "ping localhost:8080"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # TODO: Clean up image.
      - uses: actions/checkout@v4
      - run: |
          momo --version
      - name: Run momo upload app
        run: |
          momo upload app test testdata/test.apk
      - name: Run momo get app
        run: |
          sleep 9
          momo get app test
